### ISSUE TITLE
Update the frontend

### ISSUE THREAD

**Issue by SaintAngeLs** [SaintAngeLs/courier_app#10]
The problem of the login is only based on the problem frontend service update

**Comment by eggwhat** [comment]
Can you expand on what the problem with login is?

**Comment by SaintAngeLs** [comment]
> Can you expand on what the problem with login is?
I do agree, it sounds unresolvable. To perform this step and consider the issue resolved we are supposed to have more api endpoints to obtain the ability to see something more than congrats to user, when login.

**Comment by SaintAngeLs** [comment]
This issue is closed due to no other inactivity.
