### ISSUE TITLE
CustomerNotFoundException in ParcelsService and OrdersService during creating inquiry or order

### ISSUE THREAD

**Issue by an2508374** [SaintAngeLs/courier_app#107]
In both cases customerId is in payload and then I have this exception despite the fact that customer with this id is in CustomersService repository. Parcels and Orders seems to have their owns customer repositories and maybe somewhere there is a source of that problem. Commenting some lines with checking customerId in AddParcelHandler or CreateOrderHandler allows to temporarily omit that issue.
![problem1](https://github.com/SaintAngeLs/courier_app/assets/148250180/5ae43803-1990-4868-88ee-9c4346fdab36)
![problem2](https://github.com/SaintAngeLs/courier_app/assets/148250180/c8539e30-a75e-4aab-a141-5e841debed8f)
![Problem3](https://github.com/SaintAngeLs/courier_app/assets/148250180/0885a1b8-a696-4bb5-9b15-4d56d6bafe80)

**Comment by eggwhat** [comment]
It was the issue with outbox. It should be working on external_api_integration branch, though it probably won't work with already created accounts.

**Comment by an2508374** [comment]
I can confirm that it works nice on external_api_integration with newly created accounts. Problem solved, thank you.
