### ISSUE TITLE
Adding the unit tests for the SwiftParcel.Identity

### ISSUE THREAD

**Issue by SaintAngeLs** [SaintAngeLs/courier_app#12]

**Comment by SaintAngeLs** [comment]
This issue require the new testing project creation for the Identity microservice and modules it contains and partially uses

**Comment by eggwhat** [comment]
Please review and tell me if I missed something that should be tested. https://github.com/SaintAngeLs/courier_app/pull/22

**Comment by SaintAngeLs** [comment]
This issue will we desperately reopened in the future, now it is successfully closed according to the satisfaction of the current specific needs.

**Comment by SaintAngeLs** [comment]
> Please review and tell me if I missed something that should be tested. #22

Thank you, it is nicely done. The more specific reply is inside of the discussion in the  last pull-request opened from the pp_dev branch
