### ISSUE TITLE
[Project Global update]

### ISSUE THREAD

**Issue by SaintAngeLs** [SaintAngeLs/courier_app#27]
Please, in the last pull request there are added two more services to the application. There is some divergence with the basic specification of the project. If you want to eliminate this divergence in any of the present microservices, you may add this modifications, or we may add more services and apply all the changes required latter

**Comment by eggwhat** [comment]
Can you please explain how these resource, reservation services are going to work? I am not sure if I get it.

**Comment by eggwhat** [comment]
And are we assuming orders can have more than one parcel? Will that just be an option for user to request more than one parcel at once or something else?

**Comment by SaintAngeLs** [comment]
This issue is closed due to inactivity.
