### ISSUE TITLE
Orders.Service

### ISSUE THREAD

**Issue by SaintAngeLs** [SaintAngeLs/courier_app#31]

**Comment by SaintAngeLs** [comment]
@eggwhat  Please, take a look in the Api, there are the example endpoints. I will try to help you with this service

**Comment by eggwhat** [comment]
@SaintAngeLs  I see that you pushed some changes. I am very SmArT and didn't push my code so now i have to resolve conflicts so please wait a second

**Comment by eggwhat** [comment]
Btw in our requirements we have "**_For purposes of th is project, we will reuse this page for the courier company so if the login user is a currier from your company he should have a list of this company's deli very and he can change the state of delivery to “received” with the courier name and date, “Delivered” with the courier name and date, “Cannot deliver” reason why it could be delivered, date and courier name._**". I treated it as that courier may change state to cannot deliver before and after he takes a parcel. Don't know if we agree on that.

**Comment by SaintAngeLs** [comment]
It is not quite in the direct way told, but, I think, that the courier may change no matter he has the parcel. 
@an2508374, What do you think?

**Comment by eggwhat** [comment]
Orders service is nearly finished. 

This service should probably cover getting all offers for office-worker. I don't think that we have a role for office-worker unless we consider him as an admin. Need an answer for this.

 Regarding #38 so far orders can have many parcels but that can be changed rather easily. The second matter has already been addressed.

**Comment by SaintAngeLs** [comment]
This issue is Is closed due to inactivity.
