### ISSUE TITLE
Some info after my conversation with Sulmar

### ISSUE THREAD

**Issue by an2508374** [SaintAngeLs/courier_app#38]
I've consulted today with our supervisor and asked some questions about matters which were unclear for us in the last few days:

**1.** We don't have to consider that the order can have more than one parcel. It would be very complicated then, so we can assume that we have one to one relationship between parcels and orders.
**2.** We have requirement: "For purposes of this project, we will reuse this page for the courier company so if the login user is a currier from your company he should have a list of this company's delivery and he can change the state of delivery to “Received” with the courier name and date, “Delivered” with the courier name and date, “Cannot deliver” reason why it could be delivered, date and courier name."
In general, full logic of that requirement must be provided, for example courier may change status to "Cannot deliver" only after changing its state to "Received".  Moreover, the courier may change status to "Delivered" also only after changing its state to "Received". Next, "Delivered" is the last state of the order and we cannot turn back to "Received" or "Cannot deliver". I indicated only some examples, more similar rules can be pointed there.
**3.** It isn't necessary to use SQL database, we can use only Mongo or other NoSQL concept without any problems.

I recommend paying attention to the above issues as soon as it is possible.

**Comment by SaintAngeLs** [comment]
@an2508374, thank you, we get it
