### ISSUE TITLE
Identity, Customers and Couriers surveces [ update ]

### ISSUE THREAD

**Issue by SaintAngeLs** [SaintAngeLs/courier_app#43]
We need to provide the changes to this services, as basicly, I assumed that there are 3 separate roles absolutely, but courier should aso have the functionality to make on order. It needs less clarification than working out in this services

**Comment by eggwhat** [comment]
What do you mean by "courier should have the functionality to make an order"?

**Comment by SaintAngeLs** [comment]
> What do you mean by "courier should have the functionality to make an order"?

Sorry, my previous assumption was not correct, I misunderstood " company so if the login user is a currier from your company he should have a list of this company's delivery and he can change the state of delivery to “Received” with the courier name and date, “Delivered” with the courier name and date, “Cannot deliver” reason why it could be delivered, date and courier name" from the issue #38  it as the courier should also have to make an order as a clinet,

**Comment by SaintAngeLs** [comment]
This issue is closed due to no other inactivity.
